Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -19,11 +19,19 @@ jobs:
       - name: Extract Version from winutil.ps1
         id: extract_version
         run: |
-          $content = Get-Content ./winutil.ps1
-          $version = ($content -match 'Version\s*:\s*(\d{2}\.\d{2}\.\d{2})') | Out-Null
-          $version = $matches[1]
-          echo "##[set-output name=version;]$version"
-        shell: pwsh        
+          $version = ''
+          Get-Content ./winutil.ps1 -TotalCount 10 | ForEach-Object {
+            if ($_ -match 'Version\s*:\s*(\d{2}\.\d{2}\.\d{2})') {
+              $version = $matches[1]
+              echo "##[set-output name=version;]$version"
+              break
+            }
+          }
+          if (-not $version) {
+            Write-Error "Version not found in winutil.ps1"
+            exit 1
+          }
+        shell: pwsh       
 
       - name: Create Release
         id: create_release
